#!/bin/sh
ssh -t -t ubuntu@3.35.139.226<<EOF
    cd ~/jenkins-tutorial
    sudo -s	
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 14.17.1	
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF